Casestudy/Controllers/BrandController.cs
using Microsoft.AspNetCore.Mvc;
using Casestudy.Models;
using System.Collections.Generic;
using Casestudy.Utils;
using System;
namespace Casestudy.Controllers
{
    public class BrandController : Controller
    {
        AppDbContext _db;
        public BrandController(AppDbContext context)
        {
            _db = context;
        }
        public IActionResult Index(BrandViewModel vm)
        {
            // only build the catalogue once
            if (HttpContext.Session.Get<List<Brand>>(SessionVars.Brands) == null)
            {
                // no session information so let's go to the database
                try
                {
                    BrandModel braModel = new BrandModel(_db);
                    // now load the categories
                    List<Brand> brands = braModel.GetAll();
                    HttpContext.Session.Set<List<Brand>>(SessionVars.Brands, brands);
                    vm.SetBrands(brands);
                }
                catch (Exception ex)
                {
                    ViewBag.Message = "Catalogue Problem - " + ex.Message;
                }
            }
            else
            {
                // no need to go back to the database as information is already in the session
                vm.SetBrands(HttpContext.Session.Get<List<Brand>>(SessionVars.Brands));
                ProductModel ProdModel = new ProductModel(_db);
                vm.Products = ProdModel.GetAllByBrand(vm.Id);
            }
            return View(vm);
        }
        public IActionResult SelectBrand(BrandViewModel vm)
        {
            BrandModel brandModel = new BrandModel(_db);
            ProductModel productModel = new ProductModel(_db);
            List<Product> products = productModel.GetAllByBrand(vm.BrandId);
            List<ProductViewModel> vms = new List<ProductViewModel>();
            if (products.Count > 0)
            {
                foreach (Product product in products)
                {
                    ProductViewModel mvm = new ProductViewModel();
                    mvm.Qty = 0;
                    mvm.BrandId = vm.BrandId;
                    mvm.BrandName = brandModel.GetName(vm.BrandId);
                    mvm.ProductName = product.ProductName;
                    mvm.Price = product.Costprice;
                    mvm.MSRP = product.MSRP;
                    mvm.GraphicName = product.GraphicName;
                    mvm.Description = product.Description;
                    mvm.Id = product.Id;
                    vms.Add(mvm);
                }
                ProductViewModel[] myproduct = vms.ToArray();
                HttpContext.Session.Set<ProductViewModel[]>(SessionVars.Products, myproduct);
            }
            vm.SetBrands(HttpContext.Session.Get<List<Brand>>(SessionVars.Brands));
            return View("Index", vm); // need the original Index View here
        }

        [HttpPost]
        public ActionResult SelectProduct(BrandViewModel vm)
        {
            Dictionary<string, object> cart;
            if (HttpContext.Session.Get<Dictionary<string, Object>>(SessionVars.Cart) == null)
            {
                cart = new Dictionary<string, object>();
            }
            else
            {
                cart = HttpContext.Session.Get<Dictionary<string, object>>(SessionVars.Cart);
            }
            ProductViewModel[] products = HttpContext.Session.Get<ProductViewModel[]>(SessionVars.Products);
            String retMsg = "";
            foreach (ProductViewModel product in products)
            {
                if (product.Id == vm.ProductId)
                {
                    if (vm.Qty > 0) // update only selected product
                    {
                        product.Qty = vm.Qty;
                        retMsg = vm.Qty + " - product(s) Added!";
                        cart[product.Id] = product;
                    }
                    else
                    {
                        product.Qty = 0;
                        cart.Remove(product.Id);
                        retMsg = "product(s) Removed!";
                    }
                    vm.BrandId = product.BrandId;
                    break;
                } 
            }
            ViewBag.AddMessage = retMsg;
            HttpContext.Session.Set<Dictionary<string, Object>>(SessionVars.Cart, cart);
            vm.SetBrands(HttpContext.Session.Get<List<Brand>>(SessionVars.Brands));
            return PartialView("AddToCartPratial");
        }
    }
}

Casestudy/Controllers/CartController.cs
//////using Microsoft.AspNetCore.Mvc;
//////using Microsoft.AspNetCore.Http;
//////using System;
//////using Casestudy.Utils;
//////namespace Casestudy.Controllers
//////{
//////    public class CartController : Controller
//////    {
//////        public IActionResult Index()
//////        {
//////            return View();
//////        }
//////        public ActionResult ClearCart() // clear out current Cart
//////        {
//////            HttpContext.Session.Remove(SessionVars.Cart);
//////            HttpContext.Session.Set<String>(SessionVars.Cart, "Cart Cleared");
//////            return Redirect("/Home");
//////        }
//////    }
//////}

////using Microsoft.AspNetCore.Mvc;
////using Microsoft.AspNetCore.Http;
////using Casestudy.Utils;
////using Casestudy.Models;
////using System.Collections.Generic;
////using System;
////namespace Casestudy.Controllers
////{
////    public class CartController : Controller
////    {
////        AppDbContext _db;
////        public CartController(AppDbContext context)
////        {
////            _db = context;
////        }
////        public IActionResult Index()
////        {
////            return View();
////        }
////        public ActionResult ClearTray() // clear out current tray
////        {
////            HttpContext.Session.Remove(SessionVars.Cart);
////            HttpContext.Session.SetString(SessionVars.Message, "Cart Cleared");
////            return Redirect("/Home");
////        }
////        // Add the tray, pass the session variable info to the db
////        public ActionResult AddCart()
////        {
////            CartModel model = new CartModel(_db);
////            int retVal = -1;
////            string retMessage = "";
////            try
////            {
////                Dictionary<string, object> cartItems = HttpContext.Session.Get<Dictionary<string, object>>(SessionVars.Cart);
////                retVal = model.AddCart(cartItems, HttpContext.Session.GetString(SessionVars.User));
////                if (retVal > 0) // Tray Added
////                {
////                    retMessage = "Cart " + retVal + " Created!";
////                }
////                else // problem
////                {
////                    retMessage = "Cart not added, try again later";
////                }
////            }
////            catch (Exception ex) // big problem
////            {
////                retMessage = "Cart was not created, try again later! - " + ex.Message;
////            }
////            HttpContext.Session.Remove(SessionVars.Cart); // clear out current tray once persisted
////            HttpContext.Session.SetString(SessionVars.Message, retMessage);
////            return Redirect("/Home");
////        }
////    }
////}

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Casestudy.Utils;
using Casestudy.Models;
using System.Collections.Generic;
using System;
namespace Casestudy.Controllers
{
    public class CartController : Controller
    {
        AppDbContext _db;
        public CartController(AppDbContext context)
        {
            _db = context;
        }

        [Route("[action]")]
        public IActionResult GetCarts()
        {
            CartModel model = new CartModel(_db);
            return Ok(model.GetAll());
        }

        [Route("[action]/{tid:int}")]
        public IActionResult GetCartDetails(int tid)
        {
            CartModel model = new CartModel(_db);
            return Ok(model.GetCartDetails(tid, HttpContext.Session.GetString(SessionVars.User)));
        }

        public IActionResult Index()
        {
            return View();
        }
        public ActionResult ClearCArt() // clear out current tray
        {
            HttpContext.Session.Remove(SessionVars.Cart);
            HttpContext.Session.SetString(SessionVars.Message, "Cart Cleared");
            return Redirect("/Home");
        }
        // Add the tray, pass the session variable info to the db
        public ActionResult AddCart()
        {
            CartModel model = new CartModel(_db);
            
            string retMessage = "";
            try
            {
                Dictionary<string, object> cartItems = HttpContext.Session.Get<Dictionary<string, object>>(SessionVars.Cart);
                retMessage = model.AddCart(cartItems, HttpContext.Session.GetString(SessionVars.User));
                if (retMessage  == "") // Tray Added
                {
                    retMessage = "Cart not added, try again later";
                }
              
            }
            catch (Exception ex) // big problem
            {
                retMessage = "Cart was not created, try again later! - " + ex.Message;
            }
            HttpContext.Session.Remove(SessionVars.Cart); // clear out current Cart once persisted
            HttpContext.Session.SetString(SessionVars.Message, retMessage);
            return Redirect("/Home");
        }
        public IActionResult List()
        {
            // they can't list Carts if they're not logged on
            if (HttpContext.Session.GetString(SessionVars.User) == null)
            {
                return Redirect("/Login");
            }
            return View("List");
        }



    }
}

Casestudy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Casestudy</title>
    <link href='https://fonts.googleapis.com/css?family=Barrio' rel='stylesheet'>
    
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" style="background-color:#003B46">
        <div class="container" >
            <div class="navbar-header" >
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse pull-left"  >
             
                <ul class="nav navbar-nav " style="color:black">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index"><span class="glyphicon glyphicon-home"></span> Home</a></li>
                    <li><a asp-area="" asp-controller="Brand" asp-action="Index"><span class="glyphicon glyphicon-grain"></span>Brands</a></li>
                    <li><a href="/Cart"><span class="glyphicon glyphicon-shopping-cart"></span> View Cart</a></li>
                    <li><a asp-area="" asp-controller="Register" asp-action="Index"><span class="glyphicon glyphicon-pencil"></span>  Register</a> </li>
                    <li><a asp-area="" asp-controller="Login" asp-action="Index"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    <li><a asp-area="" asp-controller="Login" asp-action="Logoff"><span class="glyphicon glyphicon-log-out"></span> Logoff</a></li>
                    <li><a asp-area="" asp-controller="Cart" asp-action="List">Carts</a></li>
                    <li><a asp-area="" asp-controller="Branch" asp-action="Index"><span class="glyphicon glyphicon-tags"></span> Branches</a></li>
          
                </ul>
                <span style="color:white">
                    <span class="glyphicon glyphicon-certificate"></span>
                    @Context.Session.GetString(SessionVars.LoginStatus)
                </span>
            </div>
        </div>
    </nav>
    <div class="container body-content  " >
        @RenderBody()
        <hr style="color:yellow" />
    </div>
    <footer class="footer" style="margin-left:10%;margin-top:10%;">
        <p>&copy; 2018 - Info3067</p>
    </footer>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>